# Generated by Django 4.2.5 on 2023-09-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rolls',
            new_name='Roll',
        ),
    ]
